<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ApplicationManifest Condition="'$(OS)' == 'Windows_NT'">app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\Icon.ico</ApplicationIcon>
    <UseAppHost>true</UseAppHost>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.18" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.18" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.18" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\Icon.png" />
    <AvaloniaResource Include="Assets\Icon.ico" />
    <AvaloniaResource Include="Assets\CourseViewer\**\*.png" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Assets\CourseViewer\" />
  </ItemGroup>
</Project>
